### ISSUE TITLE
Footer needs to be updated

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmca-design-system#160]
**Describe the bug**
Footer needs to be updated

**To Reproduce**
1. Go to https://beta.wmca.org.uk

**Expected behavior**
Updated footer

**Screenshots**
![Screenshot 2021-05-06 at 15 27 01](https://user-images.githubusercontent.com/68856858/117315555-b5da6300-ae7f-11eb-81bf-787b2ebb88a1.png)

**Desktop (please complete the following information):**
OS: macOS
Browser: Safari
Version: 14.1

**Comment by rolorogan** [comment]
Updated footer has been released onto the beta site
