### ISSUE TITLE
Hub banner - Indented spacing

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#172]
**Describe the bug**
The heading and body content within the banner isn't in line with the rest of the page contents.

**To Reproduce**
1. Go to 'https://beta.wmca.org.uk/who-we-are

**Expected behavior**
The text should be left-aligned to the body content.

**Screenshots**
<img width="800" alt="Screenshot 2021-06-23 at 11 54 09" src="https://user-images.githubusercontent.com/66072673/123087604-a659ae00-d41c-11eb-9c02-aec8b2badb92.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Comment by rolorogan** [comment]
@sam-wmca Fixed in beta. Can you please check?
