### ISSUE TITLE
Hub banner - Responsive resizing not working

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#173]
**Describe the bug**
The hub banner component does not scale responsively and content is cut off.

**To Reproduce**
1. Go to https://beta.wmca.org.uk/who-we-are
2. Resize the page to a narrow view

**Expected behavior**
The banner should resize responsively and the image disappear - https://www.figma.com/file/NE1D76Vj3OEAcZSQGJgYmV/WMCA-Design-System?node-id=111%3A1699 

**Screenshots**
<img width="361" alt="Screenshot 2021-06-23 at 11 15 33" src="https://user-images.githubusercontent.com/66072673/123087967-136d4380-d41d-11eb-9293-c4775d2c61c8.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Comment by rolorogan** [comment]
@sam-wmca fix is released to beta. Can you please test?
