### ISSUE TITLE
HP - News spacing on mobile

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#174]
**Describe the bug**
There's inconsistent vertical spacing on smaller displays/windows between news articles

**To Reproduce**
1. Go to beta.wmca.org.uk
2. View on mobile or resize browser window
3. Scroll down to News
4. See inconsistent news spacing

**Expected behavior**
There should be 10px spacing between news images/dates, 20px between news articles.

**Screenshots**
<img width="362" alt="Screenshot 2021-06-23 at 11 15 04" src="https://user-images.githubusercontent.com/66072673/123093155-3c90d280-d423-11eb-986b-1a6d85702fbd.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Version: 14.6

**Additional context**
[Figma file with hp news article spacing](https://www.figma.com/file/O0EtkzXwhpXc6KoC6eBsnD/Homepage?node-id=1%3A500)

**Comment by rolorogan** [comment]
@sam-wmca update released to beta. Can you please check?
