### ISSUE TITLE
Header and breadcrumb links redirect to old website

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#176]
**Describe the bug**
The logo/breadcrumb links redirect to wmca.org.uk

**To Reproduce**
1. Go to https://beta.wmca.org.uk/what-we-do/
2. Click the logo in the nav bar; or the home icon in the breadcrumb
3. You are redirected to the old homepage rather than the new one

**Expected behavior**
Links should keep within the beta website and redirect to the new homepage.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Additional context**
This is a global issue.

**Comment by rolorogan** [comment]
@sam-wmca Updated on beta. can you please test?
