### ISSUE TITLE
Beta banner - update text and links

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#177]
## What
> The beta banner currently doesn't have a feedback loop integrated. Can we change the wording to:

This is a new service - your [feedback](https://surveys.hotjar.com/ed9799a8-4ee1-47d1-838c-3922a90f2eb7) will help us improve it.

## Why
> We need to gather user feedback from the new website to improve the experience iteratively.

## Anything else
> Hotjar user feedback survey: https://surveys.hotjar.com/ed9799a8-4ee1-47d1-838c-3922a90f2eb7

**Comment by rolorogan** [comment]
This feature has been released to the beta site
