### ISSUE TITLE
WMCA logo in header

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#178]
**Describe the bug**
The SVG needs to be swapped so that the interior parts of the mark are 50% transparent.

**To Reproduce**
1. Go to any page
2. Logo in the header shows lighter interior elements, they should be 50% transparent

**Expected behavior**
The interior parts of the logo should be 50% transparent.

**Screenshots**
<img width="304" alt="Screenshot 2021-06-23 at 13 48 24" src="https://user-images.githubusercontent.com/66072673/123099041-b330ce80-d429-11eb-9728-29965019cf92.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Comment by rolorogan** [comment]
@sam-wmca fix released on beta. Please test
