### ISSUE TITLE
Menu button not visible on smaller displays

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#181]
**Describe the bug**
The menu button in the nav bar is not visible. It is there and interactive.

**To Reproduce**
1. Go to beta.wmca.org.uk
2. View on a mobile or resize browser width so the navbar collapses
3. See the menu button is not visible

**Expected behavior**
The menu button should be visible so there's a visual cue.

**Screenshots**
<img width="363" alt="Screenshot 2021-06-24 at 14 54 00" src="https://user-images.githubusercontent.com/66072673/123309500-e56f2880-d51c-11eb-80ca-ade716f04ea2.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Comment by rolorogan** [comment]
@sam-wmca Fix released to beta. Can you please test?

**Comment by sam-wmca** [comment]
@rolorogan Thank you, it appears now! But it's using the system font rather than Noto Sans 🤪
<img width="112" alt="Screenshot 2021-06-28 at 19 57 43" src="https://user-images.githubusercontent.com/66072673/123689526-3a77ab00-d84b-11eb-9e5c-391348427a06.png">

**Comment by rolorogan** [comment]
@sam-wmca released and ready to test
