### ISSUE TITLE
The Mayor - logo resizing in Hub Header

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#182]
**Describe the bug**
The Mayoral mark in the hub header is too large

**To Reproduce**
1. Go to https://beta.wmca.org.uk/the-mayor-1/

**Expected behavior**
The mark should be 138px wide

**Screenshots**
<img width="556" alt="Screenshot 2021-06-24 at 18 53 00" src="https://user-images.githubusercontent.com/66072673/123309909-69c1ab80-d51d-11eb-93dd-8721c15e0bde.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Comment by rolorogan** [comment]
@sam-wmca Fix released to beta. Can you please check?
