### ISSUE TITLE
Image Content Cards - tiny border around images

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#183]
**Describe the bug**
Images have a tiny border around them on Image Content Cards, rather than filling the card's width entirely.

**To Reproduce**
1. Go to beta.wmca.org.uk
2. Scroll down to campaigns section
3. Notice 1-2px border around images on the Content Cards. It is more apparent on the right-hand side of the image.

**Expected behavior**
Images should fill the entire width of the Content Card.

**Screenshots**
<img width="1011" alt="Screenshot 2021-06-24 at 19 06 56" src="https://user-images.githubusercontent.com/66072673/123312490-5401b580-d520-11eb-86c9-9760493c5bc9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Comment by rolorogan** [comment]
@sam-wmca  released and ready to test
