### ISSUE TITLE
Button fonts not styled correctly

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#185]
**Describe the bug**
Buttons aren't pulling through the correct font and are using a generic sans-serif font

**To Reproduce**
1. Go to https://beta.wmca.org.uk/what-we-do/west-midlands-cultural-sector-research-project/west-midlands-cultural-infrastructure-map/
2. Scroll down to buttons
3. See error

**Expected behavior**
The font should be styled in Noto Sans Display Bold

**Screenshots**
<img width="590" alt="Screenshot 2021-06-25 at 17 35 59" src="https://user-images.githubusercontent.com/66072673/123457574-f6cb3a00-d5db-11eb-91b9-e458665487cb.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Comment by rolorogan** [comment]
@sam-wmca released and ready to test
