### ISSUE TITLE
Content pages - Content cards have dividers automatically

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#186]
**Describe the bug**
Content cards on content page templates have Dividers applied automatically, these should only be on Campaign pages with the option to disable them.

**To Reproduce**
1. Go to https://beta.wmca.org.uk/what-we-do/west-midlands-cultural-sector-research-project/west-midlands-cultural-infrastructure-map/
2. Scroll down to content card
3. See dividers are applied

**Expected behavior**
Content cards shouldn't have dividers styled above and below them.

**Screenshots**
<img width="1085" alt="Screenshot 2021-06-25 at 17 36 07" src="https://user-images.githubusercontent.com/66072673/123457799-342fc780-d5dc-11eb-80c6-382465f5117e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Comment by rolorogan** [comment]
@sam-wmca this should be fixed now on beta
