### ISSUE TITLE
Productivity and Skills link broken

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#187]
**Describe the bug**

**To Reproduce**
1. Go to [https://beta.wmca.org.uk/what-we-do](https://beta.wmca.org.uk/what-we-do)
2. Click on Productivity and Skills
3. See that the link doesn't work

**Expected behavior**
The link should open the Productivity and Skills hub

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Additional context**
As all Skills content moved wholly to the beta site, the content is currently inaccessible.

**Comment by rolorogan** [comment]
Fixed
