### ISSUE TITLE
[HP] Padding added when scaled below 568px

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#195]
**Describe the bug**
12px padding is added to the left and right when the browser is scaled ≤568px wide on the homepage.

**To Reproduce**
1. Go to [https://beta.wmca.org.uk](https://beta.wmca.org.uk)
2. Scale browser ≤568px or view on mobile
3. See error

**Expected behavior**
The header, footer and other components should be full width.

**Screenshots**
![IMG_3219](https://user-images.githubusercontent.com/66072673/124275346-48267c80-db3a-11eb-86f9-9809b1210b82.PNG)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Max
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Additional context**
This issue is only on the homepage and is reproducible in Chromium browsers (Chrome, Edge)

**Comment by rolorogan** [comment]
@sam-wmca fix released on beta. Please test
