### ISSUE TITLE
[HP] Content cards

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#196]
**Describe the bug**
The top 2 image content cards do not scale down on mobile and bleed off the screen

**To Reproduce**
1. Go to [https://beta.wmca.org.uk](https://beta.wmca.org.uk) on mobile
2. Scroll down to campaign section
3. The top 2 content cards bleed off the edge

**Expected behavior**
The cards should scale down to the width of the screen

**Screenshots**
![IMG_3223](https://user-images.githubusercontent.com/66072673/124276042-3d201c00-db3b-11eb-926f-6c37be15811b.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Browser: Safari
 - Version: 14.6

**Comment by rolorogan** [comment]
@sam-wmca fix released on beta. Please test

**Comment by sam-wmca** [comment]
> @sam-wmca fix released on beta. Please test

🔥
