### ISSUE TITLE
Search text is TfWM specific

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#204]
**Describe the bug**
The tip text in the search bar is populated with transport advice. Can this please be changed to:
"Search for news, campaigns, events..."

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to beta.wmca.org.uk
2. Click on Search
3. See text

**Expected behavior**
The text should relate to WMCA content

**Screenshots**
![CD4DEB63-DA94-48FC-8A65-BC088FFD5EB4-2690-00000147279C84D7](https://user-images.githubusercontent.com/66072673/124772251-c799be80-df33-11eb-81fd-90816c59598f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.6

**Comment by rolorogan** [comment]
Released to live site
