### ISSUE TITLE
Campaigns - Hyperlink issues.

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmca-design-system#223]
**Describe the bug**
A couple of issues:
- There are a number of URLs that are not hyperlinks - not sure if this is an Umbraco issue or the content editor not marking them as such. 
- We also have two colours being used to denote them - the Birmingham.gov on at the top is a standard web hyperlink colour, whereas others use our design system blue. 

**To Reproduce**
1. Go to 'https://beta.wmca.org.uk/campaigns/the-great-summer-staycation/#welcome-back.'
2. Scroll down to the accordian section at bottom of the page and open. 

**Expected behavior**
Would expect all URLs to be hyperlinks and appear with consistent styling.

**Screenshots**
![Screenshot 2021-07-22 at 11 18 31](https://user-images.githubusercontent.com/68856858/126624781-5eccf0dc-76ea-488a-bf74-9213ec38b620.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 91.0.4472.164

**Comment by rolorogan** [comment]
@Doodlepaul There was an issue adding multiple links in the accordions. This is fixed and this page has been updated by James. 

Regarding the different colours: When you visit it will change the colour. This is what was done in the TfWM DS so not changed. If you want any changes made to how the links are styled let me know.

**Comment by Doodlepaul** [comment]
@rolorogan. Cheers for this Nathan. All good and colour issue seems to have been resolved.
