### ISSUE TITLE
Space between accordions

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmca-design-system#232]
**Describe the bug**
The new revision of the accordion component does include any margin below, so that when there are multiple accordions used together, they appear in one block. Can we please add the same margin included on the previous component version.

**To Reproduce**
1. Go to '.https://beta.wmca.org.uk/what-we-do/west-midlands-cultural-sector-research-project/west-midlands-cultural-infrastructure-map/' for example of new implementation. 

2. Go to 'https://beta.wmca.org.uk/who-we-are/' to see previous component version which includes the correct margin between multiple accordions.

**Expected behavior**
There should be a margin between multiple accordions to make it easier for the user to understand.

**Screenshots**
![Newer - wrong margin](https://user-images.githubusercontent.com/68856858/128190815-6fc92e1d-2882-4259-a374-2c7f4a3946db.png)
![Previous - correct margin](https://user-images.githubusercontent.com/68856858/128190823-a6d91ff2-bc86-4609-abd8-27c7a4c8c823.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by rolorogan** [comment]
Fixed
