### ISSUE TITLE
Issues with fonts

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmca-design-system#28]
There are a few issues with fonts in the WMCA DS:
- The link text in the Nav Bar should be in DM Sans rather than Noto Sans;
- Body text/button text/everything other than headers and Nav Bar should be in Noto Sans Display, rather than Open Sans
- Headings should be DM Sans (this is already logged)
- DM Sans doesn't pull through in Safari (14) and the browser uses the default sans-serif font. Likely the same in IE but not tested. Fonts pull properly in other browsers.

**Comment by rolorogan** [comment]
All fixed
